// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    acompanhamento: {
        name: "acompanhamento";
        parameters: Record<string, never>;
        result: Array<{
          /** Nome do vendedor dono da carteira vigente do cliente (não o vendedor_id). */
          vendedor: string;
          /** @sqlType BIGINT */
          na_fila: number;
          /** @sqlType BIGINT */
          trabalhados: number;
          /** @sqlType BIGINT */
          vendeu: number;
          /** @sqlType BIGINT */
          vai_pensar: number;
          /** @sqlType BIGINT */
          sem_interesse: number;
          /** @sqlType BIGINT */
          nao_atendeu: number;
        }>;
      };
    fila: {
        name: "fila";
        parameters: {
          /** STRING - use sql.string() */
          vendedor: SQLStringMarker;
        };
        result: Array<{
          /** Nome do vendedor dono da carteira vigente do cliente (não o vendedor_id). */
          vendedor: string;
          /** Posição do cliente na fila DESTE vendedor - reinicia em 1 por vendedor. Use no lugar de LIMIT parametrizado. */
          ordem: number;
          /** Cliente a ligar. INT, alinhado a gold.score_propensao e ao parâmetro p_cliente_id das funções gold.*. */
          cliente_id: number;
          /** Nome do cliente. */
          razao_social: string;
          /** Cidade do cliente. */
          cidade: string;
          /** UF do cliente. */
          uf: string;
          /** Score de propensão de compra em 7 dias (0 a 1), de gold.score_propensao. */
          score: number;
          /** Faixa do score (Fria/Morna/Quente/Muito quente), de gold.score_propensao. */
          faixa: string;
          /** Ticket médio histórico do cliente, de gold.features_cliente. */
          ticket_medio: number;
          /** Frase em português explicando por que ligar agora, derivada das features do cliente (valor, lançamento, atraso de ritmo). O CASE avalia do sinal mais raro para o mais comum de propósito. */
          motivo: string;
          /** SKU mais comprado pelo cliente na marca preferida dele, ainda não recomprado nos últimos 90 dias, com o saldo do snapshot mais recente de silver.estoque. NULL quando não há candidato. */
          sugestao: string;
          /** Resultado da ligação: vendeu | vai_pensar | sem_interesse | nao_atendeu. */
          status_retorno: string;
          /** Texto livre do vendedor sobre a ligação - contexto que não cabe no status. */
          comentario_retorno: string;
        }>;
      };
    kpis_semana: {
        name: "kpis_semana";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          contatos: number;
          /** @sqlType BIGINT */
          vendedores: number;
          /** @sqlType DOUBLE */
          receita_esperada: number;
          /** @sqlType DATE */
          referencia: string;
          /** @sqlType BIGINT */
          acertos_top200: number;
          /** @sqlType DOUBLE */
          lift_top200: number;
          /** @sqlType DOUBLE */
          taxa_base: number;
          /** @sqlType BIGINT */
          ja_trabalhados: number;
          /** @sqlType BIGINT */
          viraram_pedido: number;
        }>;
      };
    vendedores: {
        name: "vendedores";
        parameters: Record<string, never>;
        result: Array<{
          /** Nome do vendedor dono da carteira vigente do cliente (não o vendedor_id). */
          vendedor: string;
          /** @sqlType BIGINT */
          contatos: number;
        }>;
      };
  }
}
